updated script

diff --git a/templates/scripts/bin/bench b/templates/scripts/bin/bench
--- a/templates/scripts/bin/bench
+++ b/templates/scripts/bin/bench
@@ -8,25 +8,25 @@ PROGNAME="$(basename $0)"
 VERSION="v0.0.1"
 
 # Helper functions for guards
-# error(){
-#   error_code=$1
-#   echo "ERROR: $2" >&2
-#   echo "($PROGNAME wrapper version: $VERSION, error code: $error_code )" &>2
-#   exit $1
-# }
-# check_cmd_in_path(){
-#   cmd=$1
-#   which $cmd > /dev/null 2>&1 || error 1 "$cmd not found!"
-# }
+error(){
+  error_code=$1
+  echo "ERROR: $2" >&2
+  echo "($PROGNAME wrapper version: $VERSION, error code: $error_code )" &>2
+  exit $1
+}
+check_cmd_in_path(){
+  cmd=$1
+  which $cmd > /dev/null 2>&1 || error 1 "$cmd not found!"
+}
 
 # Guards (checks for dependencies)
-#check_cmd_in_path docker
+check_cmd_in_path docker
 #check_cmd_in_path docker-machine
 #docker-machine active > /dev/null 2>&1 || error 2 "No active docker-machine VM found."
 
 # Set up mounted volumes, environment, and run our containerized command
 exec docker run \
   --interactive --tty --rm \
-  --volume "$PWD":/wd \
-  --workdir /wd \
+  --volume "$PWD/bench.config.json"/:/tool/bench.config.json \
+  --workdir /tool \
   "registry.gitlab.com/cyberos/infrastructure/bench-tool:latest" "$@"
